plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

description = 'ERP Lite - Multi-module project for Spring Boot 4 and Spring Framework 7 with Java 25'

allprojects {
    group = 'com.udemy'
    version = '0.0.1-SNAPSHOT'
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    repositories {
        mavenCentral()
    }

    dependencyManagement {
        imports {
            mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
        }
    }

    dependencies {
        // librerias que van a heredar todos los modulos

        // lombok
        compileOnly 'org.projectlombok:lombok:1.18.46'
        annotationProcessor 'org.projectlombok:lombok:1.18.46'

        // MapStruct
        implementation("org.mapstruct:mapstruct:1.6.3")
        annotationProcessor("org.mapstruct:mapstruct-processor:1.6.3")

        // Binding Lombok Mapstruct
        implementation("org.projectlombok:lombok-mapstruct-binding:0.2.0")


        //JUnit para todos los modulos
        //testImplementation 'org.junit.jupiter:unit-jupiter:5.11.0'

        // testing
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform() // Esto configura JUnit 5 automáticamente de forma correcta
    }
}
