spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${APPLICATION_NAME}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: ${MAIL_PROPERTIES_SMTP_AUTH}
      mail.smtp.starttls.enable: ${MAIL_PROPERTIES_STARTTLS_ENALABLE}
      mail.smtp.starttls.required: ${MAIL_PROPERTIES_STARTTLS_REQUIRED}
      mail.smtp.ssl.trust: ${MAIL_HOST}
      mail.debug: false

  # PostgreSQL
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    hikari:
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE}
      minimum-idle: ${HIKARI_MINIMUM_IDLE}

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    open-in-view: ${JPA_OPEN_IN_VIEW}
    properties:
      hibernate:
        dialect: ${JPA_HIBERNATE_DIALECT}
        format_sql: ${JPA_HIBERNATE_FORMAT_SQL}
        use_sql_comments: ${JPA_HIBERNATE_USE_SQL_COMMENTS}

  # MongoDB - Spring Boot 4.x
  data:
    mongodb:
      auto-index-creation: ${MONGO_AUTO_INDEX_CREATION}

    # Redis
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: ${REDIS_TIMEOUT}
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE}
          max-idle: ${REDIS_POOL_MAX_IDLE}
          min-idle: ${REDIS_POOL_MIN_IDLE}

  mongodb:
    uri: ${MONGODB_URI}

  web:
    error:
      include-message: ${MONGODB_INCLUDE_MESSAGE}
      include-binding-errors: ${MONGODB_INCLUDE_BINDING_ERRORS}
      include-stacktrace: ${MONGODB_INCLUDE_STACKTRACE}

# Server
server:
  port: ${SERVER_PORT}

# Logging
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}
    com.erp: ${LOG_LEVEL_APP}
    org.springframework.web: ${LOG_LEVEL_WEB}
    org.springframework.data: ${LOG_LEVEL_DATA}
    org.hibernate.SQL: ${LOG_LEVEL_SQL}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_SQL_PARAMS}
    org.mongodb.driver: ${LOG_LEVEL_MONGO}